Updated how-to bridge docs
galacticcouncil/HydraDX-docs pull request #174
Opened 2023-09-28 02:12 UTC by degengami

Added in Moonbeam Bridge how-to and updated Acala Bridge how-to

2023-09-28 08:17 UTC, lolmcshizz commented on docs/howto_bridge.md
> +- Once the tokens are approved for transfer, click **Send Tokens (5). T**his starts the bridging process cross-chain.
T**his? ** in wrong place

2023-09-28 08:18 UTC, lolmcshizz commented on docs/howto_bridge.md
> +- Once the transaction has been processed by Wormhole, click **Redeem Tokens (5).** This action results in you receiving the tokens on the Acala chain.
You still have to "redeem" the tokens? This doesn't use an auto-relayer? What does the user do once they're on the Acala chain? The UI should abstract the next step out for them to appear on HydraDX?

2023-09-28 08:19 UTC, lolmcshizz commented on docs/howto_bridge.md
> +- Bind your two wallets following [Acala's guide](https://guide.acalaapps.wiki/general/address-binding). Completing this action will require a small amount ACA.
small amount of ACA

2023-09-28 08:22 UTC, lolmcshizz requested changes

2023-09-28 08:22 UTC, lolmcshizz commented on docs/howto_bridge.md
> +- Once the transaction has been processed by Wormhole, click **Redeem Tokens (5).** This action results in you receiving the tokens on the Acala chain.
Okay it seems it should be "Redeem & route tokens" - this action results in you receiving the tokens on the HydraDX chain.

2023-09-28 08:22 UTC, lolmcshizz commented on docs/howto_bridge.md
> +- Within **Settings** **(5)**, you can select whether to Auto Relay the transaction.
Shouldn't this step be urging the user to select this? otherwise I'm guessing they won't be auto routed to HydraDX?

2023-09-28 08:51 UTC, degengami reviewed
revised

2023-10-03 09:03 UTC, lolmcshizz approved these changes

2023-10-03 09:04 UTC, merged