Rewrite Snakenet
galacticcouncil/HydraDX-docs pull request #67
Opened 2021-04-23 23:46 UTC by vgantchev

2021-04-25 09:39 UTC, SimonKraus requested changes

2021-04-25 09:39 UTC, SimonKraus commented on docs/snakenet.md
> +Beyond staking rewards, Snakenet brings a big bag of incentives for community involvement. HydraDX is community-driven and all contributions are rewarded in proportion to their added value. Community
```suggestion
Beyond staking rewards, Snakenet brings a big bag of incentives for community involvement. HydraDX is community-driven and all contributions are rewarded in proportion to their added value. Community contributions can take various shapes. The biggest bounties are reserved for finding (and ideally - fixing) critical bugs in the chain. Community building, content creation and i18n are other examples of activities that are rewarded. More detailed information on community incentives will follow soon after we finalize the integration with Commonwealth which will allow us to handle the treasury tips. Needless to say, all early contributions will be rewarded retroactively.
```

2021-04-25 21:14 UTC, jak-pan commented on docs/snakenet.md
> +Snakenet provides an opportunity for all Hydraheads to gear up as we progress towards mainnet. Validators and nominators can get used to playing their role in the [staking](/staking) process and earn
```suggestion
Snakenet provides an opportunity for all Hydraheads to gear up as we progress towards mainnet. Validators and nominators can get used to playing their role in the [staking](/staking) process and earn rewards of approximately **50% APY**. Developers can put their code to action in a testnet environment, and we can monitor how the network behaves under this increased activity.
```

2021-04-26 05:20 UTC, SimonKraus approved these changes

2021-04-26 05:23 UTC, merged